create table if not exists feedback
(
    id int generated by default as identity,
    feedback text not null,
    source varchar(2048) not null,
    created_at timestamp with time zone default now(),
    day_of_streak smallint not null,
    primary key(id)
);
