create table if not exists feedback_mood
(
    id int generated by default as identity,
    feedback_id int not null,
    mood_id int not null,

    primary key(id),

    constraint fk_feedback_mood_feedback_id
        foreign key(feedback_id)
        references feedback(id),

    constraint fk_feedback_mood_mood_id
        foreign key(mood_id)
        references mood(id)
);
