version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - ./tables:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
