version: "3.9"
services:
  api:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - ./tables:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
